public enum Specialization
{
    Allergist,
    Cardiologist,
    Dermatologist,
    Endocrinologist,
    Gastroenterologist,
    Hematologist,
    Nephrologist,
    Neurologist,
    Oncologist,
    Ophthalmologist,
    Orthopedist,
    Otolaryngologist,
    Pediatrician,
    Psychiatrist,
    Pulmonologist,
    Rheumatologist,
    Urologist
}
